--- 
apiVersion: v1
kind: Pod
metadata: 
  name: Hello-Pod
spec: 
  containers: 
    - 
      image: "nginx:1.14.2"
      name: nginx
      ports: 
        - 
          ContainerPort: 80
    - 
      env: 
        - 
          name: MYSQL_ROOT_PASSWORD
          value: Password@123
      image: "mysql:5.7"
      name: mysql
      ports: 
        - 
          ContainerPort: 3306
